"""esquema inicial

Revision ID: 6f7ea6220e69
Revises: 
Create Date: 2026-09-15 23:03:17.546258
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '6f7ea6220e69'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('student', 'teacher', 'administrator', name='role', native_enum=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    op.create_table('event_detection',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('plate', sa.String(length=16), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('authorized', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('image_s3_key', sa.String(length=512), nullable=True),
    sa.Column('camera_id', sa.String(length=64), nullable=True),
    sa.Column('gate_opened', sa.Boolean(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('event_uuid', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_uuid')
    )
    with op.batch_alter_table('event_detection', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_detection_plate'), ['plate'], unique=False)
        batch_op.create_index('ix_event_plate_detected', ['plate', 'detected_at'], unique=False)

    op.create_table('list_car',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plate', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('list_car', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_list_car_plate'), ['plate'], unique=True)
        batch_op.create_index(batch_op.f('ix_list_car_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('list_car', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_list_car_user_id'))
        batch_op.drop_index(batch_op.f('ix_list_car_plate'))

    op.drop_table('list_car')
    with op.batch_alter_table('event_detection', schema=None) as batch_op:
        batch_op.drop_index('ix_event_plate_detected')
        batch_op.drop_index(batch_op.f('ix_event_detection_plate'))

    op.drop_table('event_detection')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
